# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11QSjjFX_K6TPm9olVeDr-ikG7j-r5OQG
"""

import os

IMAGE_PATH = "../Data/IDC_Data"

BASE_PATH = "../Data/Split"

TRAIN_PATH = os.path.sep.join([BASE_PATH, "taining"])
VAL_PATH = os.path.sep.join([BASE_PATH, "validation"])
TEST_PATH = os.path.sep.join([BASE_PATH, "testing"])

TRAIN_SPLIT = 0.75
VAL_SPLIT = 0.1
TEST_SPLIT = 0.1

MODEL_PATH = "../Data/Model/original_model.model"


#create a list of patient names
